export enum RefundStatus {
  REQUESTED = 'REQUESTED',
  PENDING = 'PENDING',
  PROCESSED = 'PROCESSED',
  PARTIALLY_PROCESSED = 'PARTIALLY_PROCESSED',
  FAILED = 'FAILED',
  DECLINED = 'DECLINED',
  CANCELLED = 'CANCELLED'
}
